set(_CATKIN_CURRENT_PACKAGE "state_est_control")
set(state_est_control_VERSION "0.0.0")
set(state_est_control_MAINTAINER "yisha <yisha@todo.todo>")
set(state_est_control_PACKAGE_FORMAT "1")
set(state_est_control_BUILD_DEPENDS "std_msgs" "roscpp" "geometry_msgs" "message_generation" "cmake_modules" "nodelet")
set(state_est_control_BUILD_EXPORT_DEPENDS "std_msgs" "roscpp" "geometry_msgs" "message_runtime" "cmake_modules" "nodelet")
set(state_est_control_BUILDTOOL_DEPENDS "catkin")
set(state_est_control_BUILDTOOL_EXPORT_DEPENDS )
set(state_est_control_EXEC_DEPENDS "std_msgs" "roscpp" "geometry_msgs" "message_runtime" "cmake_modules" "nodelet")
set(state_est_control_RUN_DEPENDS "std_msgs" "roscpp" "geometry_msgs" "message_runtime" "cmake_modules" "nodelet")
set(state_est_control_TEST_DEPENDS )
set(state_est_control_DOC_DEPENDS )
set(state_est_control_DEPRECATED "")